// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "TaskTracker.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::ntu::cap;

class TaskTrackerHandler : virtual public TaskTrackerIf {
public:
    TaskTrackerHandler() {
        // Your initialization goes here
    }

    void ping(std::string& _return) {
        // Your implementation goes here
        printf("ping\n");
    }

    int64_t create_table(const TableProperty& table_property) {
        // Your implementation goes here
        printf("create_table\n");
    }

    int64_t create_cf(const std::string& table_name, const ColumnFamilyProperty& cf_property) {
        // Your implementation goes here
        printf("create_cf\n");
    }

    int64_t vector_put_int(const std::string& table_name, const int64_t shard_id, const std::string& cf_name, const std::vector<std::string> & row_key, const std::vector<std::string> & column_key, const std::vector<int64_t> & value) {
        // Your implementation goes here
        printf("vector_put_int\n");
    }

    int64_t vector_put_double(const std::string& table_name, const int64_t shard_id, const std::string& cf_name, const std::vector<std::string> & row_key, const std::vector<std::string> & column_key, const std::vector<double> & value) {
        // Your implementation goes here
        printf("vector_put_double\n");
    }

    int64_t vector_put_string(const std::string& table_name, const int64_t shard_id, const std::string& cf_name, const std::vector<std::string> & row_key, const std::vector<std::string> & column_key, const std::vector<std::string> & value) {
        // Your implementation goes here
        printf("vector_put_string\n");
    }

    int64_t vector_merge_int(const std::string& table_name, const int64_t shard_id, const std::string& cf_name, const std::vector<std::string> & row_key, const std::vector<std::string> & column_key, const std::vector<int64_t> & value) {
        // Your implementation goes here
        printf("vector_merge_int\n");
    }

    int64_t vector_merge_double(const std::string& table_name, const int64_t shard_id, const std::string& cf_name, const std::vector<std::string> & row_key, const std::vector<std::string> & column_key, const std::vector<double> & value) {
        // Your implementation goes here
        printf("vector_merge_double\n");
    }

    int64_t vector_merge_string(const std::string& table_name, const int64_t shard_id, const std::string& cf_name, const std::vector<std::string> & row_key, const std::vector<std::string> & column_key, const std::vector<std::string> & value) {
        // Your implementation goes here
        printf("vector_merge_string\n");
    }

    int64_t timed_vector_put_int(const std::string& table_name, const int64_t shard_id, const std::string& cf_name, const std::vector<std::string> & row_key, const std::vector<std::string> & column_key, const int64_t time_stampe, const std::vector<int64_t> & value) {
        // Your implementation goes here
        printf("timed_vector_put_int\n");
    }

    int64_t timed_vector_put_double(const std::string& table_name, const int64_t shard_id, const std::string& cf_name, const std::vector<std::string> & row_key, const std::vector<std::string> & column_key, const int64_t time_stampe, const std::vector<double> & value) {
        // Your implementation goes here
        printf("timed_vector_put_double\n");
    }

    int64_t timed_vector_put_string(const std::string& table_name, const int64_t shard_id, const std::string& cf_name, const std::vector<std::string> & row_key, const std::vector<std::string> & column_key, const int64_t time_stampe, const std::vector<std::string> & value) {
        // Your implementation goes here
        printf("timed_vector_put_string\n");
    }

    void vector_get_int(std::vector<int64_t> & _return, const std::string& table_name, const int64_t shard_id, const std::string& cf_name, const std::vector<std::string> & row_key, const std::vector<std::string> & column_key) {
        // Your implementation goes here
        printf("vector_get_int\n");
    }

    void vector_get_double(std::vector<double> & _return, const std::string& table_name, const int64_t shard_id, const std::string& cf_name, const std::vector<std::string> & row_key, const std::vector<std::string> & column_key) {
        // Your implementation goes here
        printf("vector_get_double\n");
    }

    void vector_get_string(std::vector<std::string> & _return, const std::string& table_name, const int64_t shard_id, const std::string& cf_name, const std::vector<std::string> & row_key, const std::vector<std::string> & column_key) {
        // Your implementation goes here
        printf("vector_get_string\n");
    }

    void scan_all_int(std::map<std::string, std::map<std::string, int64_t> > & _return, const std::string& table_name, const int64_t shard_id, const std::string& cf_name) {
        // Your implementation goes here
        printf("scan_all_int\n");
    }

    void scan_all_double(std::map<std::string, std::map<std::string, double> > & _return, const std::string& table_name, const int64_t shard_id, const std::string& cf_name) {
        // Your implementation goes here
        printf("scan_all_double\n");
    }

    void scan_all_string(std::map<std::string, std::map<std::string, std::string> > & _return, const std::string& table_name, const int64_t shard_id, const std::string& cf_name) {
        // Your implementation goes here
        printf("scan_all_string\n");
    }

    void timed_scan_int(std::map<std::string, std::map<std::string, int64_t> > & _return, const std::string& table_name, const int64_t shard_id, const std::string& cf_name, const int64_t time_stamp) {
        // Your implementation goes here
        printf("timed_scan_int\n");
    }

    void timed_scan_double(std::map<std::string, std::map<std::string, double> > & _return, const std::string& table_name, const int64_t shard_id, const std::string& cf_name, const int64_t time_stamp) {
        // Your implementation goes here
        printf("timed_scan_double\n");
    }

    void timed_scan_string(std::map<std::string, std::map<std::string, std::string> > & _return, const std::string& table_name, const int64_t shard_id, const std::string& cf_name, const int64_t time_stamp) {
        // Your implementation goes here
        printf("timed_scan_string\n");
    }

};

int main(int argc, char **argv) {
    int port = 9090;
    shared_ptr<TaskTrackerHandler> handler(new TaskTrackerHandler());
    shared_ptr<TProcessor> processor(new TaskTrackerProcessor(handler));
    shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
    shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
    shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

    TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
    server.serve();
    return 0;
}

