/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Unicap_CONSTANTS_H
#define Unicap_CONSTANTS_H

#include "Unicap_types.h"

namespace ntu {
namespace cap {

class UnicapConstants {
public:
    UnicapConstants();

};

extern const UnicapConstants g_Unicap_constants;

}
} // namespace

#endif
